### ISSUE TITLE
updated_at (when using !timestamps) not updated?

### ISSUE THREAD

**Issue by ethank** [mongomapper/mongomapper#285]
When doing atomic operations (increment and set), the "updated_at" timestamp does not seem to be updated.

Is this by design? As of now I have to explicitly set it:

``` ruby
        # update, just increment the access_count
        @show_for_storage.increment(:access_count=>1)
        # and update the returned image count (it might change)
        @show_for_storage.set(:returned_images=>instagram_results.count)
        @show_for_storage.set(:updated_at=>Time.now)
```

**Comment by sgnn7** [comment]
Wrote a patch for this:
- https://github.com/mongomapper/mongomapper/issues/610

**Comment by smtlaissezfaire** [comment]
Hmm - is this how AR or Mongoid works?  How would you perform an update without setting updated_at? I guess you'd have to drop down to the raw driver?

**Comment by sgnn7** [comment]
@smtlaissezfaire Not sure how the others work but the timestamps are explicitly needed to be set when doing a low-level MM collection command that modifiers do since they don't trigger the [timestamp](https://github.com/mongomapper/mongomapper/blob/master/lib/mongo_mapper/plugins/timestamps.rb) `before_save` callback. Why this is the case is a different topic that I don't know much about sadly.
