### ISSUE TITLE
Queries processed differently when encapsulated in method

### ISSUE THREAD

**Issue by clupprich** [mongomapper/mongomapper#604]
I guess this problem has the same underlying reason as #547 and #603, but I observed that it doesn't seem to be about lazy/eager methods, but about some general issue with the query proxies.

The following code works correctly (`Customer.no_course` is a scope using `where`):

`Customer.no_course.first(email: 'CUSTOMER1@TEST.COM'.downcase)`

This yields the correct mongo query: `MONGODB (0.2ms) customers['customers'].find({:course=>"", :email=>"customer1@test.com"}).limit(-1)`

But when I move the `.first` into its own method into `Customer.with_email`, the first condition of the query is ignored and only the email criteria is sent to Mongo:

`Customer.no_course.with_email('customer1@test.com')`

`MONGODB (0.3ms) customers['customers'].find({:email=>"customer1@test.com"}).limit(-1)`

I've created a gist for easier understanding: https://gist.github.com/clupprich/9b2ae833d7f9f0a95e2d.

**Comment by smtlaissezfaire** [comment]
yeah, it's the same as #603. 

I think the right way to solve this is with scopes (Mongoid solves this by using model.with_scope / pushing + poping hashes of queries that apply to the current model + thread).

I've got a patch coming that isn't quite ready yet.

**Comment by cheald** [comment]
So the fundamental issue here is that when you create a method like that, `self` is the model, rather than the `DecoratedPluckyQuery` that you get from a scope.

    > Customer.no_course
     => #<MongoMapper::Plugins::Querying::DecoratedPluckyQuery ...>

Calling `#with_email` on `#DecoratedPluckyQuery` calls `method_missing` on the model class, but `self` is the model class, not the `#DecoratedPluckyQuery`, so it doesn't have any of the existing criteria information!

Scopes are specifically the preferred way to solve this, because they handle the `self` rebinding:

    class Customer
      include MongoMapper::Document

      key :email, String
      key :course, String

      scope :no_course, where(course: '')
      scope :with_email, ->(email) { where(email: email.downcase) }
    end

Then you'd call `Customer.no_course.with_email(email).first` or whatnot.

The reason it works with scopes is that scopes are implemented as a Hash of lambdas, which you can then call with `instance_eval`, binding the `DecoratedPluckyQuery` as the receiver, rather than the model class. It's functionally equivalent to doing something like:

    with_email = ->(email) { where(email: email).first }
    Customer.no_course.instance_eval(&with_email, email)

In this case, the result of `#no_course` (a DecoratedPluckyQuery) is the receiver in which `with_email` is executed. You can't get this behavior with class-bound methods unless DecoratedPluckyQuery descends from the model or you unbind and rebind the method (which is doable, but ugly and hacky).

Keeping thread-local scopes attached to the model class is really tricky; in JRuby for example, Fibers are implemented with Threads, so each Fiber has its own thread local variables. If you build a MongoMapper model that is also a Celluloid actor, and then you try to implicitly scope model calls by amending the model with thread-local metadata, you aren't guaranteed to get the right scoping, and may in fact get the wrong scoping!

**Comment by smtlaissezfaire** [comment]
Yeah - agreed.

Actually, you can't even rebind in this case because it's a class (singleton) method, and ruby 1.9 (maybe 2 as well?) will throw an error if you try to rebind - unless you have evil-ruby or something similar that modifies the run time.

I think the way to do this is to actually add scope stacks to the model.  So:

```ruby
model.with_scope :first_name => "Scott" do
  model.first # => should scope to the first user named scott
end
```

This is the way mongoid solves this problem, and it seems like the right solution to me.

Otherwise, I think it's sort of unreasonable to say #first can't be called in a scope without this weird behavior.  

I've got a slug library (https://github.com/GoLearnUp/mm-sluggable) that suffers from this bug right now.  It occurs when using the association proxy, because, as you mentioned, the class method is called with method_missing and that doesn't apply the "current scope" (i.e. the association proxy)

**Comment by clupprich** [comment]
Tried with scopes, following scenario:

```ruby
class Customer
# ...
  scope :with_email, ->(email) { where(email: email.downcase).first }
  # scope :with_email, ->(email) { first(email: email.downcase) } yields the same result/error
end

Customer.with_email('test@test.com') 
# => Fails with a "NoMethodError: undefined method `criteria' for #<Customer:0x007fd8a02216d8>" in activemodel-3.2.21/lib/active_model/attribute_methods.rb:407
```

**Comment by smtlaissezfaire** [comment]
See a4bcf80c6b7dca4e1a0e5a5cad91ebf1323452ce.  Closing this one out.

**Comment by clupprich** [comment]
Nice! Thanks Scott!
