### ISSUE TITLE
Ruby 2.2.2?

### ISSUE THREAD

**Issue by smtlaissezfaire** [mongomapper/mongomapper#635]
Should we lock to a certain version of ruby?  Should that be 2.2x or should we continue to support 1.8.7 going forward?  This is really a question for @cheald

**Comment by jamieorc** [comment]
The rails world has left 1.8.7 behind. Seems reasonable that going forward, MM would only support Ruby 2.x.

**Comment by cheald** [comment]
For the next major version bump, including the Ruby 2.x driver update, I'm fine supporting 2.0+.

**Comment by Edwardzyc** [comment]
Is this project still being maintained?

**Comment by jamieorc** [comment]
Supposedly, but there's been little activity for a long time. Furthermore, Mongo now maintains both the Ruby Driver code and the Mogoid code, which driver 2.x was developed for. I'm starting to think about how to migrate to Mongoid. Not what I wanted to do, but I beginning to see no viable alternative in order to stay on MongoMapper. In the early days, Mongo clearly preferred MongoMapper to Mongoid, but Mongoid clearly won the war in the long term.

**Comment by smtlaissezfaire** [comment]
I'm still doing work on it, although haven't done anything in about 6 months time.

I've got an RC candidate that I've been running in production for a while.  I should release it.

But otherwise, I'm always open to patches.  I can dedicate some time to patch review if you mark anything as urgent.

**Comment by jamieorc** [comment]
The problem for me is that I'm full bore on work and so have no time to dig into MongoMapper to deliver updates and patches. A questions I've had is if I can add resources (people) at work, which is more desirable, devote resources to working on MM or to migrating to Mongoid. I've really liked MM a lot, which is why I've stuck with it so long.

**Comment by smtlaissezfaire** [comment]
Right.  Same here.  I'm pretty new to the contribution team, but most of the contributions happen after work.  Obviously this means I have to pick between personal time and open source time.

@cheald and others have done a great job, but I'd love to find some more resources, because I work a full time job which usually doesn't give me the flexibility to work on MM even part time.  I enjoy doing it, but I can't contribute as much as I'd like.

I'd feel bad letting this project die for a few reasons:

1. I really like MM
2. I've got a lot of infrastructure (MM plugins) that works well.
3. Re-writing apps is *hard* and not fun

Usually I find some time every few months to dig through the patches.  Otherwise, if I have an urgent bug fix, I'll just fix myself.

**Comment by smtlaissezfaire** [comment]
Ok - first steps for me are:

1. release 0.14.  it's had an rc1 which I've been running in production for 6 months or so.  I think it's all good to go.
1. getting the build server back up + running.  it's been failing on various builds for a while
1. cutting out old ruby + rails versions.  I'm going to drop support for everything before ruby 2.x and rails 3.2x
1. merge in patches / get the project working with the 2.x driver
1. I'd also like to get rails 5.x and ruby 2.3 running eventually
1. release 0.15.x
