### ISSUE TITLE
Database cleaner?

### ISSUE THREAD

**Issue by Edwardzyc** [mongomapper/mongomapper#647]
AR automatically handles this 

Do I need to use database cleaner myself to clear out the test db?

**Comment by smtlaissezfaire** [comment]
Hey @Edwardzyc.  Sorry for the delayed response.

You'll have to do it yourself.  Or you can look at something like: https://github.com/DatabaseCleaner/database_cleaner

But the code is pretty simple:

https://gist.github.com/smtlaissezfaire/d60b12d49f1dff62a06fa5a7024d4025

(You could also use drop() there, but it's up to you - if you want to preserve indexes between test runs you'll have to use remove() instead of drop()).
